services:
  db:
    image: postgres:15.2-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
    environment:
      ADMINER_DESIGN: dracula
  clockapi:
    image: jeffrygonzalez/clock-api:v1.0.0
    ports:
      - 1337:80
    environment:
      - TZ=America/New_York
      - ASPNETCORE_ENVIRONMENT=Development
volumes:
  db_data: 