apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-clock
  namespace: hypertheory
spec:
  replicas: 3
  selector:
    matchLabels:
      app: business-clock
  template:
    metadata:
      labels:
        app: business-clock
    spec:

      containers:
      - name: business-clock
        image: jeffrygonzalez/clock-api:v1.0.0
        env:
          - name: TZ
            value: "America/New_York"
          - name: ASPNETCORE_ENVIRONMENT
            value: Development

        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
